# Generated by Django 4.0.1 on 2022-02-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
