# Generated by Django 4.0.1 on 2022-02-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StoreAdmin",
            new_name="StoreOwner",
        ),
    ]
