# Generated by Django 4.0.1 on 2022-02-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_api", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
