# Generated by Django 4.0.1 on 2022-02-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model_api", "0002_rename_storeadmin_storeowner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="userID",
        ),
    ]
