# Generated by Django 4.0.1 on 2022-04-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0004_remove_order_created_remove_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateTimeCreated',
        ),
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
