# Generated by Django 4.0.1 on 2022-04-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0005_remove_order_datetimecreated_alter_order__id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateTimeCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
