# Generated by Django 4.0.1 on 2022-04-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0006_order_datetimecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateTimeCreated',
        ),
    ]
