export const DETAILED_PRODUCT_GET = "DETAILED_PRODUCT_GET";
export const DETAILED_PRODUCT_SUCCESS = "DETAILED_PRODUCT_SUCCESS";
export const DETAILED_PRODUCT_FAILURE = "DETAILED_PRODUCT_FAILURE";

export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";

export const CATEGORY_GET = "CATEGORY_GET";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
