export const DETAILED_PRODUCT_GET = "DETAILED_PRODUCT_GET"
export const DETAILED_PRODUCT_SUCCESS = "DETAILED_PRODUCT_SUCCESS"
export const DETAILED_PRODUCT_FAILURE = "DETAILED_PRODUCT_FAILURE"

export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT"
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT"

export const ENTERTAINMENT_PRODUCTS_GET = "ENTERTAINMENTS_PRODUCT_GET"
export const ENTERTAINMENT_PRODUCTS_SUCCESS = "ENTERTAINMENTS_PRODUCT_SUCCESS"
export const ENTERTAINMENT_PRODUCTS_FAILURE = "ENTERTAINMENTS_PRODUCT_FAILURE"

export const FITNESS_PRODUCTS_GET = "FITNESS_PRODUCTS_GET"
export const FITNESS_PRODUCTS_SUCCESS = "FITNESS_PRODUCTS_SUCCESS"
export const FITNESS_PRODUCTS_FAILURE = "FITNESS_PRODUCTS_FAILURE"

export const LIFESTYLE_PRODUCTS_GET = "LIFESTYLE_PRODUCTS_GET"
export const LIFESTYLE_PRODUCTS_SUCCESS = "LIFESTYLE_PRODUCTS_SUCCESS"
export const LIFESTYLE_PRODUCTS_FAILURE = "LIFESTYLE_PRODUCTS_FAILURE"

export const PETS_PRODUCTS_GET = "PETS_PRODUCTS_GET"
export const PETS_PRODUCTS_SUCCESS = "PETS_PRODUCTS_SUCCESS"
export const PETS_PRODUCTS_FAILURE = "PETS_PRODUCTS_FAILURE"

export const GAMING_PRODUCTS_GET = "GAMING_PRODUCTS_GET"
export const GAMING_PRODUCTS_SUCCESS = "GAMING_PRODUCTS_SUCCESS"
export const GAMING_PRODUCTS_FAILURE = "GAMING_PRODUCTS_FAILURE"

export const MEDICAL_PRODUCTS_GET = "MEDICAL_PRODUCTS_GET"
export const MEDICAL_PRODUCTS_SUCCESS = "MEDICAL_PRODUCTS_SUCCESS"
export const MEDICAL_PRODUCTS_FAILURE = "MEDICAL_PRODUCTS_FAILURE"
