export const DETAILED_PRODUCT_GET = "DETAILED_PRODUCT_GET"
export const DETAILED_PRODUCT_SUCCESS = "DETAILED_PRODUCT_SUCCESS"
export const DETAILED_PRODUCT_FAILURE = "DETAILED_PRODUCT_FAILURE"

export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT"
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT"

export const ENTERTAINMENT_PRODUCTS_GET = "ENTERTAINMENTS_PRODUCT_GET"
export const ENTERTAINMENT_PRODUCTS_SUCCESS = "ENTERTAINMENTS_PRODUCT_SUCCESS"
export const ENTERTAINMENT_PRODUCTS_FAILURE = "ENTERTAINMENTS_PRODUCT_FAILURE"

