name: Django CI

on:
  push:
    branches:
      - main
      - testing
      - back_end
      - front_end
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: setup_python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.2"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,md}
      - name: black_python_lint
        uses: psf/black@stable
        with:
          options: "--verbose"
      - name: Run Tests
        run: |
          python amazon/manage.py test
